// <auto-generated />
namespace MyBookingRoles.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class nameP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nameP));
        
        string IMigrationMetadata.Id
        {
            get { return "202010261338572_nameP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
